### ISSUE TITLE
ImportError: cannot import name git

### ISSUE THREAD

**Issue by lnussbaum** [oar-team/oar-docker#38]
Missing dependency on git in pip?

# oardocker init -e wheezy
Traceback (most recent call last):
  File "/usr/local/bin/oardocker", line 7, in <module>
    from oardocker.cli import main
  File "/usr/local/lib/python2.7/dist-packages/oardocker/cli.py", line 9, in <module>
    from .context import pass_context, CONTEXT_SETTINGS
  File "/usr/local/lib/python2.7/dist-packages/oardocker/context.py", line 13, in <module>
    from .state import State
  File "/usr/local/lib/python2.7/dist-packages/oardocker/state.py", line 9, in <module>
    from .utils import touch
  File "/usr/local/lib/python2.7/dist-packages/oardocker/utils.py", line 20, in <module>
    from sh import git, ErrorReturnCode
ImportError: cannot import name git

**Comment by SalemHarrache** [comment]
Hi Lucas,

Pip only handles Python packages dependancies and Git is actually optional. It is possible to use tarball instead of a git repository.

*Git needed*:

```
$ oardocker install git+https://github.com/oar-team/oar.git
$ oardocker install /path/to/oar/src
```

*Git not needed*:
```
$ oardocker install https://github.com/oar-team/oar/archive/2.5.tar.gz
$ oardocker install http://oar-ftp.imag.fr/oar/sources/stable/oar-2.5.5.tar.gz
$ oardocker install ../tarballs/oar-2.5.5+5.g493d132.tar.gz
```

However, you should not have this error for the ``oardocker init`` command.
It's been corrected and an error message should be displaying now when git is missing (only for ``oardocker install`` command).

Thank you anyway for the report.
