### ISSUE TITLE
oardocker logs -f shows bizarre errors

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#44]
I get stranged kernel output just like if the docker kernel was restarted.. and then some python errors...

```
févr. 07 21:13:29 frontend kernel: ehci-pci 0000:00:1a.0: EHCI Host Controller
févr. 07 21:13:29 frontend kernrsyslog | el: ehci-pci 0000:00:1a.0: new USB bus registered, assigned bus number 3
févr. 07 21:13:29 frontend kernel: ehci-pci 0000:00:1a.0: debug port 2
févr. 07 21:13:29 frontend kernel: ehci-pci 0000:00:1a.0: cache line size of 64 is not supported
févr. 07 21:13:29 frontend kernel: ehci-pci 0000:00:1a.0: irq 16, io mem 0xf7e38000
févr. 07 21:13:29 frontend kernel: ehci-pci 0000:00:1a.0: USB 2.0 started, EHCI 1.00
févr. 07 21:13:29 frontend kernel: usb usb3: New USB device found, idVendor=1d6b, idProduct=0002
févr. 07 21:13:29 frontend kernel: usb usb3: New USB device strings: Mfr=3, Product=2, SerialNumber=1
févr. 07 21:13:29 frontend kernel: usb usb3: Product: EHCI Host Controller
févr. 07 21:13:29 frontend kernel: usb usb3: Manufacturer: Linux 4.3.0-0.bpo.1-amd64 ehci_hcd
févr. 07 21:13:29 frontend kernel: usb usb3: SerialNumber: 0000:00:1a.0
févr. 07 21:13:29 frontend kernel: hub 3-0:1.0: USB hub found
févr. 07 21:13:29 frontend kernel: hub 3-0:1.0: 2 ports detected
févr. 07 21:13:29 frontProcess Process-216:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/neyron/.local/lib/python2.7/site-packages/oardocker/commands/cmd_logs.py", line 41, in feed
    queue.put(prefix + to_unicode(line))
  File "/home/neyron/.local/lib/python2.7/site-packages/oardocker/compat.py", line 94, in to_unicode
    return obj.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 1023: unexpected end of data
rsyslog | rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="1" x-info="http://www.rsyslog.com"] start
rsyslog | -- Logs begin at dim. 2016-02-07 21:13:29 CET. --
```

**Comment by npf** [comment]
the following lines are:

```
UnicodeDecodeError: 'utf8' codec can't decode byte 0xc3 in position 1023: unexpected end of data
rsyslog | rsyslogd: [origin software="rsyslogd" swVersion="8.4.2" x-pid="1" x-info="http://www.rsyslog.com"] start
rsyslog | -- Logs begin at dim. 2016-02-07 21:13:29 CET. --
rsyslog | févr. 07 21:13:29 frontend systemd-journald[25]: Runtime journal (/run/log/journal/) is currently using 8.0M.
rsyslog |                                                   Maximum allowed usage is set to 393.0M.
rsyslog |                                                   Leaving at least 589.4M free (of currently available 3.8G of space).
rsyslog |                                                   Enforced usage limit is thus 393.0M, of which 385.0M are still available.
rsyslog | févr. 07 21:13:29 frontend systemd-journald[25]: Missed 359 kernel messages
rsyslog | févr. 07 21:13:29 frontend kernel: pci 0000:00:19.0: reg 0x14: [mem 0xf7e39000-0xf7e39fff]
```

**Comment by npf** [comment]
also, it seems to eat all my memory ! (30% CPU + 80% MEM for the docker process with `oardocker log -f` running)
