### ISSUE TITLE
Error with bumpversion

### ISSUE THREAD

**Issue by npf** [oar-team/oar-docker#51]
As of commit e81af8ff09acd84a6711658927c6122babd24616
I have the following error with bumpversion:

```
neyron@caigang:~/scm/OAR/oardocker (master $=)$ make bumpversion
Traceback (most recent call last):
  File "scripts/bumpversion.py", line 189, in <module>
    main()
  File "scripts/bumpversion.py", line 185, in main
    args.func(args)
  File "scripts/bumpversion.py", line 50, in bump_release_version
    stderr=subprocess.STDOUT).decode('utf-8')
  File "/usr/lib/python2.7/subprocess.py", line 219, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '[u'bumpversion', u'release', u'--dry-run', u'--verbose']' returned non-zero exit status 1
Makefile:44: recipe for target 'bumpversion' failed
make: *** [bumpversion] Error 1
```

**Comment by npf** [comment]
Thanks Salem, but now I have:
```
neyron@caigang:~/scm/OAR/oardocker (master $=)$ make bumpversion 
Traceback (most recent call last):
  File "scripts/bumpversion.py", line 189, in <module>
    main()
  File "scripts/bumpversion.py", line 185, in main
    args.func(args)
  File "scripts/bumpversion.py", line 52, in bump_release_version
    current_version = m.groups(0)[0] + ".dev0"
AttributeError: 'NoneType' object has no attribute 'groups'
Makefile:44: recipe for target 'bumpversion' failed
make: *** [bumpversion] Error 1
```
:-)
